#@Author Tobechi Onwenu
#Rock, paper and scissors game. Assignment 5 project.

import turtle
import random

def main():
    global ally
    ally = turtle.Turtle()
    ally.speed(5)
    computer_chooses()
    user(ally)
def draw_rock_scissors_comp():
    ally.pu()
    ally.goto(-210,-200)
    ally.color('red')
    ally.write('Rock smashes Scissors!!!, Computer Wins.', font = ('stencil',20,'bold'))
    ally.goto(-100/2,-100/2)
    ally.pu()
    ally.goto(-100/2,-100/2)
    ally.pd()
    ally.begin_fill()
    ally.seth(60)
    ally.color('goldenrod1')
    ally.forward(200)
    ally.seth(70)
    ally.fd(100)
    ally.seth(230)
    ally.fd(100)
    ally.seth(240)
    ally.fd(200)
    ally.seth(90)
    ally.fd(35)
    ally.end_fill()
    ally.pu()
    ally.goto(100/2,-100/2)
    ally.pd()
    ally.begin_fill()
    ally.color('midnightblue')
    ally.seth(120)
    ally.forward(200)
    ally.seth(110)
    ally.fd(100)
    ally.seth(310)
    ally.fd(100)
    ally.seth(300)
    ally.fd(200)
    ally.seth(90)
    ally.fd(35)
    ally.end_fill()
    ally.pu()
    ally.goto(40,70)
    ally.pd()
    ally.begin_fill()
    ally.color('mediumaquamarine')
    ally.circle(40)
    ally.end_fill()
    ally.hideturtle()
    ally.seth(0)
    ally.clear()
def draw_rock_scissors_player():
    ally.pu()
    ally.goto(-210,-200)
    ally.color('red')
    ally.write('Rock smashes Scissors!!!, You Win.', font = ('stencil',20,'bold'))
    ally.pu()
    ally.goto(-100/2,-100/2)
    ally.pd()
    ally.begin_fill()
    ally.seth(60)
    ally.color('goldenrod1')
    ally.forward(200)
    ally.seth(70)
    ally.fd(100)
    ally.seth(230)
    ally.fd(100)
    ally.seth(240)
    ally.fd(200)
    ally.seth(90)
    ally.fd(35)
    ally.end_fill()
    ally.pu()
    ally.goto(100/2,-100/2)
    ally.pd()
    ally.begin_fill()
    ally.color('midnightblue')
    ally.seth(120)
    ally.forward(200)
    ally.seth(110)
    ally.fd(100)
    ally.seth(310)
    ally.fd(100)
    ally.seth(300)
    ally.fd(200)
    ally.seth(90)
    ally.fd(35)
    ally.end_fill()
    ally.pu()
    ally.goto(40,70)
    ally.pd()
    ally.begin_fill()
    ally.color('mediumaquamarine')
    ally.circle(40)
    ally.end_fill()
    ally.hideturtle()
    ally.seth(0)
    ally.clear()
def draw_scissors_paper_comp():
    ally.pu()
    ally.goto(-230,-150)
    ally.color('red')
    ally.write('Scissors cuts Paper!!!, Computer Wins.',font=("stencil", 20, "bold"))
    ally.pu()
    ally.goto(-100/2,-100/2)
    ally.pd()
    ally.begin_fill()
    ally.seth(60)
    ally.color('maroon')
    ally.forward(200)
    ally.seth(70)
    ally.fd(100)
    ally.seth(230)
    ally.fd(100)
    ally.seth(240)
    ally.fd(200)
    ally.seth(90)
    ally.fd(35)
    ally.end_fill()
    ally.pu()
    ally.goto(100/2,-100/2)
    ally.pd()
    ally.begin_fill()
    ally.color('purple')
    ally.seth(120)
    ally.forward(200)
    ally.seth(110)
    ally.fd(100)
    ally.seth(310)
    ally.fd(100)
    ally.seth(300)
    ally.fd(200)
    ally.seth(90)
    ally.fd(35)
    ally.end_fill()
    ally.pu()
    ally.goto(-200/2,150/2)
    ally.pd()
    ally.begin_fill()
    ally.color('yellow')
    ally.right(90)
    ally.fd(200)
    ally.left(90)
    ally.fd(100)
    ally.left(90)
    ally.fd(200)
    ally.left(90)
    ally.fd(100)
    ally.end_fill()
    ally.hideturtle()
    ally.seth(0)
    ally.clear()
def draw_scissors_paper_player():
    ally.pu()
    ally.goto(-230,-150)
    ally.color('red')
    ally.write('Scissors cuts Paper!!!, You Win.',font=("stencil", 20, "bold"))
    ally.pu()
    ally.goto(-100/2,-100/2)
    ally.pd()
    ally.begin_fill()
    ally.seth(60)
    ally.color('maroon')
    ally.forward(200)
    ally.seth(70)
    ally.fd(100)
    ally.seth(230)
    ally.fd(100)
    ally.seth(240)
    ally.fd(200)
    ally.seth(90)
    ally.fd(35)
    ally.end_fill()
    ally.pu()
    ally.goto(100/2,-100/2)
    ally.pd()
    ally.begin_fill()
    ally.color('purple')
    ally.seth(120)
    ally.forward(200)
    ally.seth(110)
    ally.fd(100)
    ally.seth(310)
    ally.fd(100)
    ally.seth(300)
    ally.fd(200)
    ally.seth(90)
    ally.fd(35)
    ally.end_fill()
    ally.pu()
    ally.goto(-200/2,150/2)
    ally.pd()
    ally.begin_fill()
    ally.color('yellow')
    ally.right(90)
    ally.fd(200)
    ally.left(90)
    ally.fd(100)
    ally.left(90)
    ally.fd(200)
    ally.left(90)
    ally.fd(100)
    ally.end_fill()
    ally.hideturtle()
    ally.seth(0)
    ally.clear()   
def draw_paper_rock_comp():
    ally.pu()
    ally.goto(-230,-150)
    ally.color('red')
    ally.write('Paper wraps Rock!!!, Computer Wins.',font=("stencil", 20, "bold"))
    ally.pu()
    ally.goto(-100/2,-100/2)
    ally.pd()
    ally.begin_fill()
    ally.color('goldenrod4')
    ally.circle(45)
    ally.end_fill()
    ally.pu()
    ally.goto(-320/2,-200/2)
    ally.pd()
    ally.begin_fill()
    ally.color('lightseagreen')
    ally.forward(250)
    ally.left(90)
    ally.forward(200)
    ally.left(90)
    ally.forward(250)
    ally.left(90)
    ally.forward(200)
    ally.left(90)
    ally.end_fill()
    ally.pu()
    ally.hideturtle()
    ally.seth(0)
    ally.clear()
def draw_paper_rock_player():
    ally.pu()
    ally.goto(-230,-150)
    ally.color('red')
    ally.write('Paper wraps Rock!!!, You Win.',font=("stencil", 20, "bold"))
    ally.pu()
    ally.goto(-100/2,-100/2)
    ally.pd()
    ally.begin_fill()
    ally.color('goldenrod4')
    ally.circle(45)
    ally.end_fill()
    ally.pu()
    ally.goto(-320/2,-200/2)
    ally.pd()
    ally.begin_fill()
    ally.color('lightseagreen')
    ally.forward(250)
    ally.left(90)
    ally.forward(200)
    ally.left(90)
    ally.forward(250)
    ally.left(90)
    ally.forward(200)
    ally.left(90)
    ally.end_fill()
    ally.pu()
    ally.hideturtle()
    ally.seth(0)
    ally.clear()
def draw_error():
    ally.pu()
    ally.hideturtle()
    ally.goto(100,0)
    ally.pd()
    ally.begin_fill()
    ally.color('red')
    for circle in range (8):
        for inner in range (2):
            ally.fd(10)
            ally.left(45)
        ally.fd(100)
        ally.right(45)
    ally.end_fill()
    ally.goto(-100,50)
    ally.color('white')
    ally.write('ERROR',font = ('stencil',30,'bold'))
    ally.seth(0)
    ally.clear()   
def draw_draw():
    ally.pu()
    ally.hideturtle()
    ally.goto(100,0)
    ally.pd()
    ally.begin_fill()
    ally.color('green')
    for circle in range (8):
        for inner in range (2):
            ally.fd(10)
            ally.left(45)
        ally.fd(100)
        ally.right(45)
    ally.end_fill()
    ally.goto(-75,50)
    ally.color('white')
    ally.write('DRAW',font = ('stencil',30,'bold'))
    ally.seth(0)
    ally.clear()   
def computer_chooses():
    game_choices = ['rock','paper','scissors']
    computer_choice = game_choices[random.randint(0,2)]
    return computer_choice
def user(game):
    user_choice =''
    while user_choice != 'end':
        comp_choice = computer_chooses()
        window = game.getscreen()
        user_choice = window.textinput("Lets play a game, type 'end' to Stop.",'Enter your choice of rock, paper or scissors here: ')
        while user_choice not in ['rock','paper','scissors','end']:
            draw_error()
            user_choice = window.textinput("Lets play a game, type 'end' to Stop",'Enter your choice of rock, paper or scissors here: ')
        if user_choice == 'rock' and comp_choice == 'scissors':
            draw_rock_scissors_player()
        elif user_choice == 'scissors' and comp_choice == 'rock':
            draw_rock_scissors_comp()
        elif user_choice == 'scissors' and comp_choice == 'paper':
            draw_scissors_paper_player()
        elif user_choice == 'paper' and comp_choice == 'scissors':
            draw_scissors_paper_comp()
        elif user_choice == 'paper' and comp_choice == 'rock':
            draw_paper_rock_player()
        elif user_choice == 'rock' and comp_choice == 'paper':
            draw_paper_rock_comp()
        elif user_choice == comp_choice:
            draw_draw()         
main()
