import turtle

my_turtle=turtle.Turtle()
my_turtle.forward(200)
my_turtle.right(90)
my_turtle.hideturtle()
my_turtle.forward(100)
my_turtle.right(45)
my_turtle.forward(100)
my_turtle.right(135)
my_turtle.forward(50)
my_turtle.showturtle()
my_turtle.left(90)
my_turtle.forward(20)
my_turtle.penup()
my_turtle.forward(10)
my_turtle.pendown()
my_turtle.forward(20)
my_turtle.left(90)
my_turtle.forward(50)
my_turtle.right(135)
my_turtle.forward(110)
my_turtle.right(45)
my_turtle.forward(100)
my_turtle.showturtle()
turtle.done()
