import turtle
scissors = turtle.Turtle()

scissors.pu()
scissors.goto(-65,70)
scissors.pd()
scissors.begin_fill()
scissors.color('yellow')
scissors.fd(200)
scissors.left(90)
scissors.fd(100)
scissors.left(90)
scissors.fd(200)
scissors.left(90)
scissors.fd(100)
scissors.end_fill()
scissors.pu()
scissors.goto(-50,-50)
scissors.begin_fill()
scissors.color('maroon')
scissors.seth(45)
scissors.pd()
scissors.forward(200)
scissors.seth(60)
scissors.fd(100)
scissors.seth(220)
scissors.fd(100)
scissors.seth(225)
scissors.fd(200)
scissors.left(90)
scissors.fd(35)
scissors.end_fill()
scissors.pu()
scissors.goto(150,-30)
scissors.pd()
scissors.begin_fill()
scissors.color('purple')
scissors.seth(135)
scissors.pd()
scissors.forward(200)
scissors.seth(140)
scissors.fd(100)
scissors.seth(300)
scissors.fd(100)
scissors.seth(315)
scissors.fd(200)
scissors.left(90)
scissors.fd(35)
scissors.end_fill()
scissors.hideturtle()
scissors.goto(-10,-80)
scissors.write('Sciccors cuts paper!!!')



